Studentmediene/kapina-frontend

- app/components/Episode/index.js
- app/containers/Post/index.js
- app/containers/Show/index.js
- package.json
This PR fixes the bug where all dates in Safari on iOS and desktop were showing "NaN.NaN.NaN"
> Use moment instead of Date library

- package-lock.json
- src/components/Episode/index.js
- src/components/Show/index.js
- src/utils/dataFormatters.js
- src/utils/dateUtils.js
- src/utils/tests/dateUtils.test.js
The `publishAt` field was forgotten in the dataTransformer, and thus the posts and episodes were not sorted correctly on a Show page. Model is now updated to use the `publishAt` field for sorting episodes/posts and as header text in episodes.
> Fix wrong date in episode posts

- src/components/Post/index.js
- src/index.js
The small date below the title on the post page was only showing the current date. It now displays the date the post was published.
> Display publishAt below post title

- src/components/Episode/index.js
- src/components/Episode/tests/__snapshots__/index.test.js.snap
- src/components/Episode/tests/index.test.js
- src/components/Show/sagas.js
- src/utils/dataFormatters.js
BLOCKED BY: https://github.com/Studentmediene/revolt-backend/pull/10
This PR makes the Episode component use the `title` field from the Episode model in GraphQL. GraphQL is responsible for returning the correct `title` value, based on a new field `use_title` in the database model.
> Custom episode titles

- src/components/FrontPage/sagas.js
- src/components/Post/index.js
- src/components/Post/sagas.js
- src/components/PostPreview/index.js
- src/components/PostPreview/styles.css
- src/components/PostPreview/tests/__snapshots__/index.test.js.snap
- src/components/PostPreview/tests/index.test.js
- src/components/PostPreviewList/tests/__snapshots__/index.test.js.snap
- src/components/PostPreviewList/tests/index.test.js
- src/utils/dataFormatters.js
BLOCKED BY: https://github.com/Studentmediene/revolt-backend/pull/11
Categories are now displayed as overlays on images for posts on the frontpage. Also displayed as a list on the detailed page for each post.
> Display categories

- src/components/Post/index.js
- src/components/Post/summernote-video-attributes.css
BLOCKED BY: https://github.com/Studentmediene/revolt-backend/pull/12 (No compatibility problems, but nothing will happen without the other PR)
This PR makes responsive videos from Django-Summernote render correctly on all screen sizes.
To review PR:
Use revolt-backend to create a post with a responsive video element. Check out the post with kapina-frontend.
> Make embedded videos responsive

- src/components/App/index.js
- src/routes.js
Renders a plain page without header and footer component if the url extender starts with /plainpage:slug. For iOS app.
> Add plain page for articles without header and footer

- src/components/FrontPage/sagas.js
- src/components/PostPreview/index.js
- src/components/PostPreview/tests/__snapshots__/index.test.js.snap
- src/components/PostPreview/tests/index.test.js
- src/components/Show/sagas.js
- src/utils/dataFormatters.js
Automatically chooses the best size based on browser width using `srcset`.
Blocked by https://github.com/Studentmediene/kapina-backend/pull/15.
> Use cropped version of images for post

- src/components/Sendeplan/styles.css
Change width of the daily table in sendeplan from 30% to 200px due to 30% of the parent div caused the text width to be greater than the table width on smaller screens, leading to text floating outside the table.
> Change sendeplan daily table width from 30% to 200px

- internals/webpack/webpack.prod.babel.js
Should make it easier to debug errors in production, especially when looking at errors reported to Sentry.
> Enable source maps in production

- src/index.js
I thought it did this by default, but apparantly not.
> Only enable sentry if in production

- internals/webpack/webpack.prod.babel.js
- src/index.js
This should finally solve our cache problems. 
The page has to reload for the new service worker to start.
> Automatically update service worker if new version is detected

- .travis.yml
Updates the Travis configuration, so that it posts updates to MS Teams instead of Slack
> build: update Travis config

- src/index.js
Failing to register a serviceworker on non-supported cleint account for about 100 errors per month in Sentry.
> fix: add check if serviceworker is supported

- package-lock.json
- src/components/Player/components/AudioControls.css
- src/components/Player/components/AudioControls.js
- src/components/Player/index.js
Disables the forward and backward buttons if either the player is playing from live, or if the url is undefined, meaning it hasen't been initiated yet.
> KAP-152: disable prev next buttons

- src/components/Player/components/PlayPauseButton.scss
lead-teksten i episode havnet for langt til venstre og blendet sammen med playbutton, etter published at blei lagt til i episode komponenten. Fant ikke hvor feilen lå, men fikset den med med flex shrink
> fixed minor flexbox problem in episode

- src/components/Player/sagas.js
Fixes the bug problem where the player can't play/pause when `https://api.radiorevolt.no/v2/sendinger/currentshows` is unavailable. This is a separate API to `kapina-backend`, and is only used to fetch information about what's currently playing. The API being unavailable does not have a large impact on the site, and should therefore not have a noticeable impact on the sites functions.
> fix: add try/catch block when fetching current show

- package-lock.json
- package.json
- public/robots.txt
- server/index.js
- server/robots.js
- server/sitemap.js
Adds an endpoint to dynamically generate all page URLs in a sitemap, to help crawlers while indexing the page. Should only be used in production (Not beta, as this will increase the ranking of the beta site in search results).
> feat: add sitemap for crawlers

- src/components/Footer/tests/__snapshots__/index.test.js.snap
- src/components/Post/styles.scss
Changed the width of the articles from 1000px to 700px. 
Should it be smaller, wider or is it good now?
The page becomes a bit empty, but hopefully the text becomes more readable. 
It is more space between the text and the SoMe buttons. Is that alright or should we try to move the buttons closer to the text?
Used px instead of % so we don't get all the whitespace on smaller screens where the width already is small enough.
> change width of post in frontend

- src/components/FrontPage/components/NewestEpisodes/styles.scss
- src/components/ShowList/ShowPreview/styles.scss
as @santi pointed out in my last PR " Fixed alignment for shows with long names #270 ". Only font-sizes should use rem and em as sizing units.
> changed margin unit from rem to px
